version: 2

references:

  ## Workspace

  workspace: &workspace
    ~/workspace

  ## Cache

  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Docker image configurations

  jdk_config: &jdk_config
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=false

jobs:
  build:
    <<: *jdk_config
    steps:
      - checkout

      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --refresh-dependencies --stacktrace
      - *save_cache

      - run:
          name: Assembling
          command: ./gradlew assemble --refresh-dependencies --stacktrace --scan

      - run:
          name: Saving jars
          command: |
            mkdir -p ~/jars/
            find . -type f -regex ".*/build/libs/.*jar" -exec cp {} ~/jars/ \;
          when: always

      - store_artifacts:
          path: ~/jars
          destination: jars

  verify:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache

      - run:
          name: Verifying
          command: ./gradlew check --stacktrace

      - run:
          name: Saving test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ./jdroid-gradle-googleplay-publisher-plugin/build/reports/tests/test
          destination: jdroid-gradle-googleplay-publisher-plugin/tests

      - store_artifacts:
          path: ./jdroid-java-googleplay-publisher/build/reports/tests/test
          destination: jdroid-java-googleplay-publisher/tests

  deploy:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache

      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew uploadArchives -PLOCAL_UPLOAD=false --stacktrace

workflows:
  version: 2
  commit:
    jobs:
      - build
      - verify:
          requires:
            - build
      - deploy:
          requires:
            - verify