version: 2.1

references:

  working_dir: &working_dir
                 ~/project

executors:
  jdk_executor:
    working_directory: *working_dir
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=false

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - v2-gradle_cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}-{{ checksum "buildSrc/src/main/kotlin/Libs.kt" }}-{{ checksum "buildSrc/src/main/kotlin/BuildLibs.kt" }}
            - v2-gradle_cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}
            - v2-gradle_cache-

  save_gradle_cache:
    steps:
      - save_cache:
          key: v2-gradle_cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ .Branch }}-{{ checksum "buildSrc/src/main/kotlin/Libs.kt" }}-{{ checksum "buildSrc/src/main/kotlin/BuildLibs.kt" }}
          paths:
            - ~/.gradle

jobs:

  gradleCache:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --stacktrace
      - save_gradle_cache

  ktlint:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Ktlint
          command: ./gradlew ktlint --stacktrace

  security:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Verify the integrity of the Gradle Wrapper JAR
          command: |
            # https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification
            cd gradle/wrapper
            gradleVersion=$(grep "distributionUrl" gradle-wrapper.properties | grep -Po "(\d+\.)+\d+")
            curl --location --output gradle-wrapper.jar.sha256 https://services.gradle.org/distributions/gradle-${gradleVersion}-wrapper.jar.sha256
            echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
            sha256sum --check gradle-wrapper.jar.sha256

  build:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Assembling
          command: ./gradlew assemble --stacktrace
      - run:
          name: Saving jars
          command: |
            mkdir -p ~/jars/
            find . -type f -regex ".*/build/libs/.*jar" -exec cp {} ~/jars/ \;
          when: always
      - store_artifacts:
          path: ~/jars
          destination: jars

  verify:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Verifying
          command: ./gradlew check --stacktrace
      - run:
          name: Saving test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

  publish:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew uploadArchives -PLOCAL_UPLOAD=false --stacktrace

  upgradeDependencies:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Upgrade Dependencies
          command: ./gradlew upgradeDependencies -PpullRequestEnabled=true --stacktrace

workflows:
  commit:
    jobs:
      - gradleCache
      - security
      - build:
          requires:
            - gradleCache
      - ktlint:
          requires:
            - build
      - verify:
          requires:
            - build
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - verify
            - ktlint
            - security
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgradeDependencies